### ISSUE TITLE
Stats by level

### ISSUE THREAD

**Issue by SergioROJ** [DMOHelper/DMOHelper#1]
I think it would be cool if stats could be calculated for lvl 99, 120 and 130 and 140, so you can see all the progressions.

**Comment by DMOHelper** [comment]
Hey there. I sadly have to inform you, that I stopped playing roughly a year ago due to bad game developers (long story short: lost an SSS+ item due to a bug in the Shop system, when they investigated my ticket, they blamed it on me and banned my whole account shortly after for illegal activities LOL). As a result, I will not publish any updates to this software.

However, as the project is open-source, feel free to add the feature you want. dmowiki still has the info for lvl. 120, 130 and 140 on [this site](https://dmowiki.com/Stat_Formula) (and it's [page history](https://dmowiki.com/index.php?title=Stat_Formula&action=history)).

The info for lvl 140 is stored [here](https://github.com/DMOHelper/DMOHelper/blob/master/csvResources/statformula.csv), you need to add the other info and an option in the UI to switch between the values.

As a final notice however, please note, that the level has only a real small impact on the final stats (e.g. an lvl 140 NA Jogress only gains 8 raw AT points against a 130. Even with all possible buffs, this would probably only end in ~50-100 more AT). The main impact in stats does the Digimon Size, which is why you always should aim for at least 137%+. The main reason why it is important to level to 140 is to not have level disadvantage against strong enemies, because you with each level difference between you and the enemy the chance to miss hits will increase exponentially.
